name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone Rotalysis Repository
        run: |
          git clone https://github.com/Unmask06/rotalysis.git
      
      - name: Copy HTML files to Rotalysis Application
        run: |
          cp -r core/* src/
          cd rotalysis
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add app/docs/
          git commit -m "Update documentation"
          git push
