name: Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Rotalysis Repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git clone https://Unmask06:${{ secrets.PAT }}@github.com/Unmask06/rotalysis.git

      - name: Ensure Destination Directory Exists in Rotalysis
        run: mkdir -p rotalysis/src

      - name: Copy Documentation Files
        run: cp -r core rotalysis/src/ # Adjust "core/" path as needed if it's located elsewhere

      - name: Configure Git User
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
        working-directory: rotalysis

      - name: Stage Documentation Changes
        run: git add -A
        working-directory: rotalysis

      - name: Commit Documentation Changes
        run: git commit -m "Update documentation!"
        working-directory: rotalysis

      - name: Push Changes to Rotalysis Repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: git push
        working-directory: rotalysis
